name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=infra init
      - name: Terraform Plan
        run: terraform -chdir=infra plan -out=tfplan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra apply -auto-approve tfplan

  build-lambda:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Package Lambda
        run: |
          cd src/processor
          pip install -r requirements.txt -t package
          cp lambda_handler.py package/
          cd package
          zip -r ../lambda.zip .
      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: src/processor/lambda.zip
